// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plxlssxaqswvgalpjeut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBseGxzc3hhcXN3dmdhbHBqZXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTAwNTMsImV4cCI6MjA3MzE4NjA1M30.iWOxSTWke7O4XRS0Aeubsj0aaByV4w496zgHSGwuVb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});